### ISSUE TITLE
dem 插值

### ISSUE THREAD

**Issue by ryry886** [FreeGIS/dem2terrain#6]
![image](https://github.com/FreeGIS/dem2terrain/assets/36318585/c62b5caa-7281-41d8-90ff-766d52f62a1f)
拉近后，阶梯层叠状，这是由于dem精度低导致的吗，用的30m高程数据。 可以自动插值，使之平滑吗？

**Comment by FreeGIS** [comment]
可能是精度太高导致的，使用90m高程数据看看。 rgb编码地形，r的权重太大了，一点点平滑过去，就飞了，先用90m试试。。。

**Comment by ryry886** [comment]
> 可能是精度太高导致的，使用90m高程数据看看。 rgb编码地形，r的权重太大了，一点点平滑过去，就飞了，先用90m试试。。。

谢谢，我找到原因了，差不多也是这个原因，不切到15级就好了，切到12级就正常了。

**Comment by cweibo** [comment]
> 您好，我运行了您的代码，左侧是使用qgis进行数据切片，右侧是使用代码进行数据切片。10级之前的切片完全正常，11级开始的切片就开始马赛克化了，我查了一下数据精度，发现11级所需的数据精度小于数据的数据精度时，该算法的运行结果就不是特别正常。这是因为没有插值算法导致的吗？ ![93ad2d0d38f17b4db09ee4612622428](https://user-images.githubusercontent.com/57380028/246739624-ecd04de5-326e-4d94-9397-2fa978334401.png)

兄弟左边的 QGIS 切片用的什么工具呢？

**Comment by FreeGIS** [comment]
> 您好，我运行了您的代码，左侧是使用qgis进行数据切片，右侧是使用代码进行数据切片。10级之前的切片完全正常，11级开始的切片就开始马赛克化了，我查了一下数据精度，发现11级所需的数据精度小于数据的数据精度时，该算法的运行结果就不是特别正常。这是因为没有插值算法导致的吗？ ![93ad2d0d38f17b4db09ee4612622428](https://user-images.githubusercontent.com/57380028/246739624-ecd04de5-326e-4d94-9397-2fa978334401.png)

是这样，采用的是最近邻插值，因此，当数据精度只能12级别，但是你切13级别，切片精度超过数据精度了，那么最近邻插值的现象就会特别明显，类似图上其他网格状。  其他引擎切图我没测试，不知道qgis那个图能不能显示地形，这个地形特别敏感，很容易显示异常

**Comment by FreeGIS** [comment]
最新的2.2.1版本已经解决插值问题，支持用户设置多种采样。
