### ISSUE TITLE
类似dem越界导致的异常现象

### ISSUE THREAD

**Issue by doucullen** [FreeGIS/dem2terrain#8]
您好，我在使用90m的dem切地形，生成的是5-13级的地形 ，原数据dem最大值为4000左右最小值为-8000左右，在生成的瓦片中出现了这样的现象。靠近一些的高层级瓦片正常，缩小后的底层级瓦片有类似尖刺的情况，我怀疑是不是存储的数据类型越界了导致的，请问地形是short类型的所有以高程限制吗

![Uploading 地形异常.png…]()

**Comment by FreeGIS** [comment]
通常地形是int16类型，范围是覆盖你这个-8000到4000的，因此不是数据类型导致的。

**Comment by FreeGIS** [comment]
2.2.0及以上版本已经解决尖刺问题，更新版本就可以解决。
